"""Añade campo created a Post

Revision ID: 7423037545f5
Revises: d5dc6b59c4ee
Create Date: 2022-01-24 21:39:08.233544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7423037545f5'
down_revision = 'd5dc6b59c4ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'created')
    # ### end Alembic commands ###
